#!/usr/bin/env python3
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 5:
        print("usage: embed_asset.py INPUT OUTPUT SYMBOL MIME", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    symbol = sys.argv[3]
    mime = sys.argv[4]

    data = src.read_bytes()
    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="ascii") as f:
        f.write("/* generated by tools/embed_asset.py */\n")
        f.write(f"static const char {symbol}_mime[] = \"{mime}\";\n")
        f.write(f"static const unsigned char {symbol}_data[] = {{\n")
        for i in range(0, len(data), 12):
            row = data[i:i + 12]
            f.write("\t")
            f.write(", ".join(f"0x{b:02x}" for b in row))
            f.write(",\n")
        f.write("};\n")
        f.write(f"static const unsigned int {symbol}_size = {len(data)};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
